# -*- coding: utf-8 -*-
"""Doctolib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUMv2Jxkzuz_NDNVL0n1ZJfl98vvfAMQ
"""
"""
# Bienvenue sur le monitoring de Doctolib!
"""

import urllib.request, urllib.error, urllib.parse
import requests
import time
from bs4 import BeautifulSoup
from tqdm import tqdm
import random
import streamlit as st

main_url = "https://www.doctolib.fr/dentiste/paris-75012?page="
request_list = [
	{"url":"https://www.doctolib.fr/blanchiment-des-dents/paris-75012?page=", "address":"Paris 12", "requete": "Blanchiment dentaire"},
  {"url":"https://www.doctolib.fr/dentiste/paris-75012?page=", "address":"Paris 12", "requete": "Dentiste"},
  {"url":"https://www.doctolib.fr/facette-dentaire/paris-75012?page=", "address":"Paris 12", "requete": "Facette dentaire"},
  {"url":"https://www.doctolib.fr/resurfacage/paris-75012?page=", "address":"Paris 12", "requete": "Surfaçage"},
  {"url":"https://www.doctolib.fr/parodontiste/paris-75012?page=", "address":"Paris 12", "requete": "Parodontie"},
  {"url":"https://www.doctolib.fr/parodontite/paris-75012?page=", "address":"Paris 12", "requete": "Parodontite"},
  {"url":"https://www.doctolib.fr/gingivite/paris-75012?page=", "address":"Paris 12", "requete": "Gingivite"},
  {"url":"https://www.doctolib.fr/freinectomie/paris-75012?page=", "address":"Paris 12", "requete": "Freinectomie"},
  {"url":"https://www.doctolib.fr/couronne-dentaire/paris-75012?page=", "address":"Paris 12", "requete": "Couronne dentaire"},
  {"url":"https://www.doctolib.fr/bruxisme/paris-75012?page=", "address":"Paris 12", "requete": "Bruxisme"},
  {"url":"https://www.doctolib.fr/gouttiere-dentaire/paris-75012?page=", "address":"Paris 12", "requete": "Gouttière dentaire"},
  {"url":"https://www.doctolib.fr/chirurgie-des-dents-de-sagesse/paris-75012?page=", "address":"Paris 12", "requete": "Chirurgie des dents de sagesse"},
  {"url":"https://www.doctolib.fr/carie-dentaire/paris-75012?page=", "address":"Paris 12", "requete": "Carie"},
  {"url":"https://www.doctolib.fr/protheses-dentaires-fixes-ou-amovibles/paris-75012?page=", "address":"Paris 12", "requete": "Prothèse dentaire fixe ou amovible"},
  {"url":"https://www.doctolib.fr/extraction-dentaire/paris-75012?page=", "address":"Paris 12", "requete": "Extraction dentaire"},
  {"url":"https://www.doctolib.fr/alignement-dentaire-invisible/paris-75012?page=", "address":"Paris 12", "requete": "Alignement dentaire invisible"},
  {"url":"https://www.doctolib.fr/prothese-sur-implant/paris-75012?page=", "address":"Paris 12", "requete": "Prothèse sur implant"}
]
debug = False

def finder_on_page(url_to_parse):
    position = 0
    counter = 0
    for link in url_to_parse.find_all("a", {"class": "dl-search-result-name"}):
        if debug == True:
          print(link.get('href'))
        if link.get('href') != "/dentiste/paris/phoebe-kamioner-chelles":
            counter = counter + 1
        else:
            counter = counter + 1
            position = counter
            return position

def page_downloader(url_to_download):
    html_text = requests.get(url_to_download).text
    soup = BeautifulSoup(html_text, 'html.parser')
    return soup

def finder_multiple_pages(main_url): 
    main_counter = 0
    page = 1
    while main_counter == 0:
        url_to_parse = main_url + str(page)
        html = page_downloader(url_to_parse)
        on_page = finder_on_page(html)
        if on_page != None:
          main_counter = on_page + ((page - 1) * 10)
        if debug == True:
          print(main_counter)
        page = page + 1
        time.sleep(random.randrange(2, 10))
        if page == 11:
          main_counter = 100
          return main_counter
    return main_counter

finder_multiple_pages(main_url)

def finder_multiple_request(list_of_requests):
  for i in tqdm(list_of_requests):
    result = finder_multiple_pages(i["url"])
    print(i["requete"], i["address"], " : ", result)
    st.echo(i["requete"], i["address"], " : ", result)
finder_multiple_request(request_list)
